### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Soomvaar#14]
> ## Description
> Create a Code of Conduct which the Mentors and Participants must abide by.
> 
> ## Additional Details
> * Mention the Standards which everyone should abide by on welcoming and inclusive language including constructive criticism.
> * Add the required responsibilities for Project Maintainers.
> * Mention the Scope of this Code of Conduct.

**Comment by aakankshabhende** [comment]
Can I work on this issue? @Ayush7614

**Comment by Ayush7614** [comment]
@aakankshabhende you are participant of DCP

**Comment by aakankshabhende** [comment]
Yes @Ayush7614
