### ISSUE TITLE
Social Media Ads

### ISSUE THREAD

**Issue by dilroseR** [Ayush7614/Soomvaar#140]
Goal: To classify whether a customer would purchase or not depending on their age, estimated salary and other factors

**Comment by suy1968** [comment]
Please Assign me as I am a contributor in Devincept @dilroseR

**Comment by dilroseR** [comment]
> Please Assign me as I am a contributor in Devincept @dilroseR

im a contributor itself of DCP and i want to solve this issue.
I'm waiting for mentors to assign it to me

**Comment by Ayush7614** [comment]
> Please Assign me as I am a contributor in Devincept @dilroseR

@suy1968 Suryansh work on different issue because @dilroseR was asked first
