### ISSUE TITLE
FACE_EYE_DETECTION

### ISSUE THREAD

**Issue by anubhav201241** [Ayush7614/Soomvaar#18]
I want to contribute to your project under DCP'21 
I want to add Face_eye and nose Detection part to your repository with the help of open cv and Python

@Ayush7614 Kindly assign this issue to me :)

**Comment by Ayush7614** [comment]
@anubhav201241 what is the status it has been 15 days

**Comment by anubhav201241** [comment]
@Ayush7614  sorry for the inconvenience, I'm not able to create pull requests on time due to some issue. I will update you with my PR by today itself

**Comment by anubhav201241** [comment]
@Ayush7614 I have created a Pull request please review it and mege it thank you :)
