### ISSUE TITLE
Startup Profit Prediction 

### ISSUE THREAD

**Issue by Jagannath8** [Ayush7614/Soomvaar#34]
**TITLE**
Startup Profit Prediction 

**DATASET**
 https://www.kaggle.com/karthickveerakumar/startup-logistic-regression

**AIM**
The aim is to predict Profit of the Startups.

**APPROACH**
I'll use ML algorithms to predict Profit of the Startups.

Assign me this issue under DCP'21.

**Comment by Ayush7614** [comment]
@Jagannath8 what is the status
