### ISSUE TITLE
Olympic Medal Prediction

### ISSUE THREAD

**Issue by Akash20x** [Ayush7614/Soomvaar#57]
I want to add model of Olympic Medal Prediction to predict whether a given athlete will win the medal or not at the Olympics based on their characteristics. I will different classification machine learning algorithms and compare their accuracy. 

I will use 120 years of Olympic history: athletes and results kaggle dataset for predictions. 

Dataset Link:
https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results

Please assign me this issue as a part of DCP'21.

**Comment by Ayush7614** [comment]
@Akash20x what is the status

**Comment by Akash20x** [comment]
I added the fork repo, just send pull request after writing readme, I will send it in an hour.
