### ISSUE TITLE
Mention all the Datasets in The README section

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Soomvaar#6]
* Like from different different platforms we have take datasets so we have mention all the datasets in the README section

**Comment by devkumar24** [comment]
Can I work on this issue?

**Comment by Ayush7614** [comment]
@devkumar24 you are part of DCP program

**Comment by Ayush7614** [comment]
@devkumar24 you are part of DCP or not

**Comment by devkumar24** [comment]
> @devkumar24 you are part of DCP or not

Yes I am part of DCP
